// <auto-generated />
namespace ShwasherSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update0114 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update0114));
        
        string IMigrationMetadata.Id
        {
            get { return "202001140305500_Update0114"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
