// <auto-generated />
namespace ShwasherSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class uv01132 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uv01132));
        
        string IMigrationMetadata.Id
        {
            get { return "202001130531315_uv0113-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
