// <auto-generated />
namespace ShwasherSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class uv02021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uv02021));
        
        string IMigrationMetadata.Id
        {
            get { return "202002021257086_uv0202-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
