// <auto-generated />
namespace ShwasherSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class uv01131 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uv01131));
        
        string IMigrationMetadata.Id
        {
            get { return "202001130529081_uv0113-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
