// <auto-generated />
namespace ShwasherSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class uv01142 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uv01142));
        
        string IMigrationMetadata.Id
        {
            get { return "202001140406099_uv0114-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
